PATCH http://localhost:8080/api/user/changePassword
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "oldPassword": "oldpassword",
  "newPassword": "20260218",
  "confirmPassword": "20260218"
}