server:
  port: 8080

spring:
  config:
    import: keys.properties

  datasource:
    url: jdbc:mysql://localhost:3306/arlist
    username: cacc
    password: 20230612
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
