server:
  port: 8080

spring:
  config:
    import: keys.properties

  datasource:
    url: jdbc:postgresql://localhost:5432/arlist
    username: postgres
    password: 20230612
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
